<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CurrenciesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('currencies')->delete();
        
        \DB::table('currencies')->insert(array (
            0 => 
            array (
                'id' => 1,
                'code' => 'DZD',
                'name' => 'Algerian Dinar',
                'symbol' => 'د.ج',
                'country' => 'Algeria',
                'cf_code' => 'DZ',
                'conversion_rate' => '129.60',
                'is_active' => 1,
                'created_at' => '2026-01-05 18:51:58',
                'updated_at' => '2026-03-07 23:57:06',
            ),
            1 => 
            array (
                'id' => 2,
                'code' => 'AOA',
                'name' => 'Angolan Kwanza',
                'symbol' => 'Kz',
                'country' => 'Angola',
                'cf_code' => 'AO',
                'conversion_rate' => '921.20',
                'is_active' => 1,
                'created_at' => '2026-01-05 18:51:58',
                'updated_at' => '2026-01-05 18:51:58',
            ),
            2 => 
            array (
                'id' => 3,
                'code' => 'XOF',
                'name' => 'West African CFA Franc',
                'symbol' => 'Fr',
                'country' => 'Benin',
                'cf_code' => 'BJ',
                'conversion_rate' => '558.00',
                'is_active' => 1,
                'created_at' => '2026-01-05 18:51:58',
                'updated_at' => '2026-01-05 18:51:58',
            ),
            3 => 
            array (
                'id' => 4,
                'code' => 'BWP',
                'name' => 'Botswana Pula',
                'symbol' => 'P',
                'country' => 'Botswana',
                'cf_code' => 'BW',
                'conversion_rate' => '13.40',
                'is_active' => 1,
                'created_at' => '2026-01-05 18:51:58',
                'updated_at' => '2026-01-05 18:51:58',
            ),
            4 => 
            array (
                'id' => 5,
                'code' => 'XOF',
                'name' => 'West African CFA Franc',
                'symbol' => 'Fr',
                'country' => 'Burkina Faso',
                'cf_code' => 'BF',
                'conversion_rate' => '558.00',
                'is_active' => 1,
                'created_at' => '2026-01-05 18:51:58',
                'updated_at' => '2026-01-05 18:51:58',
            ),
            5 => 
            array (
                'id' => 6,
                'code' => 'BIF',
                'name' => 'Burundian Franc',
                'symbol' => 'FBu',
                'country' => 'Burundi',
                'cf_code' => 'BI',
                'conversion_rate' => '2944.00',
                'is_active' => 1,
                'created_at' => '2026-01-05 18:51:58',
                'updated_at' => '2026-01-05 18:51:58',
            ),
            6 => 
            array (
                'id' => 7,
                'code' => 'XAF',
                'name' => 'Central African CFA Franc',
                'symbol' => 'Fr',
                'country' => 'Cameroon',
                'cf_code' => 'CM',
                'conversion_rate' => '1.00',
                'is_active' => 1,
                'created_at' => '2026-01-05 18:51:58',
                'updated_at' => '2026-01-05 18:51:58',
            ),
            7 => 
            array (
                'id' => 8,
                'code' => 'CVE',
                'name' => 'Cape Verde Escudo',
                'symbol' => '$',
                'country' => 'Cape Verde',
                'cf_code' => 'CV',
                'conversion_rate' => '95.90',
                'is_active' => 1,
                'created_at' => '2026-01-05 18:51:58',
                'updated_at' => '2026-01-05 18:51:58',
            ),
            8 => 
            array (
                'id' => 9,
                'code' => 'XAF',
                'name' => 'Central African CFA Franc',
                'symbol' => 'Fr',
                'country' => 'Central African Republic',
                'cf_code' => 'CF',
                'conversion_rate' => '1.00',
                'is_active' => 1,
                'created_at' => '2026-01-05 18:51:58',
                'updated_at' => '2026-01-05 18:51:58',
            ),
            9 => 
            array (
                'id' => 10,
                'code' => 'XAF',
                'name' => 'Central African CFA Franc',
                'symbol' => 'Fr',
                'country' => 'Chad',
                'cf_code' => 'TD',
                'conversion_rate' => '1.00',
                'is_active' => 1,
                'created_at' => '2026-01-05 18:51:58',
                'updated_at' => '2026-01-05 18:51:58',
            ),
            10 => 
            array (
                'id' => 11,
                'code' => 'KMF',
                'name' => 'Comorian Franc',
                'symbol' => 'CF',
                'country' => 'Comoros',
                'cf_code' => 'KM',
                'conversion_rate' => '426.50',
                'is_active' => 1,
                'created_at' => '2026-01-05 18:51:58',
                'updated_at' => '2026-01-05 18:51:58',
            ),
            11 => 
            array (
                'id' => 12,
                'code' => 'CDF',
                'name' => 'Congolese Franc',
                'symbol' => 'FC',
            'country' => 'Congo (DRC)',
                'cf_code' => 'CD',
                'conversion_rate' => '2430.00',
                'is_active' => 1,
                'created_at' => '2026-01-05 18:51:58',
                'updated_at' => '2026-01-05 18:51:58',
            ),
            12 => 
            array (
                'id' => 13,
                'code' => 'XAF',
                'name' => 'Central African CFA Franc',
                'symbol' => 'Fr',
            'country' => 'Congo (Republic)',
                'cf_code' => 'CG',
                'conversion_rate' => '1.00',
                'is_active' => 1,
                'created_at' => '2026-01-05 18:51:58',
                'updated_at' => '2026-01-05 18:51:58',
            ),
            13 => 
            array (
                'id' => 14,
                'code' => 'XOF',
                'name' => 'West African CFA Franc',
                'symbol' => 'Fr',
                'country' => 'Côte d\'Ivoire',
                'cf_code' => 'CI',
                'conversion_rate' => '558.00',
                'is_active' => 1,
                'created_at' => '2026-01-05 18:51:58',
                'updated_at' => '2026-01-05 18:51:58',
            ),
            14 => 
            array (
                'id' => 15,
                'code' => 'DJF',
                'name' => 'Djiboutian Franc',
                'symbol' => 'Fdj',
                'country' => 'Djibouti',
                'cf_code' => 'DJ',
                'conversion_rate' => '178.45',
                'is_active' => 1,
                'created_at' => '2026-01-05 18:51:58',
                'updated_at' => '2026-01-05 18:51:58',
            ),
            15 => 
            array (
                'id' => 16,
                'code' => 'EGP',
                'name' => 'Egyptian Pound',
                'symbol' => 'E£',
                'country' => 'Egypt',
                'cf_code' => 'EG',
                'conversion_rate' => '30.50',
                'is_active' => 1,
                'created_at' => '2026-01-05 18:51:58',
                'updated_at' => '2026-01-05 18:51:58',
            ),
            16 => 
            array (
                'id' => 17,
                'code' => 'ERN',
                'name' => 'Eritrean Nakfa',
                'symbol' => 'Nfk',
                'country' => 'Eritrea',
                'cf_code' => 'ER',
                'conversion_rate' => '15.00',
                'is_active' => 1,
                'created_at' => '2026-01-05 18:51:58',
                'updated_at' => '2026-01-05 18:51:58',
            ),
            17 => 
            array (
                'id' => 18,
                'code' => 'SZL',
                'name' => 'Swazi Lilangeni',
                'symbol' => 'L',
                'country' => 'Eswatini',
                'cf_code' => 'SZ',
                'conversion_rate' => '1.00',
                'is_active' => 1,
                'created_at' => '2026-01-05 18:51:58',
                'updated_at' => '2026-01-05 18:51:58',
            ),
            18 => 
            array (
                'id' => 19,
                'code' => 'ETB',
                'name' => 'Ethiopian Birr',
                'symbol' => 'Br',
                'country' => 'Ethiopia',
                'cf_code' => 'ET',
                'conversion_rate' => '1.00',
                'is_active' => 1,
                'created_at' => '2026-01-05 18:51:58',
                'updated_at' => '2026-01-05 18:51:58',
            ),
            19 => 
            array (
                'id' => 20,
                'code' => 'GMD',
                'name' => 'Gambian Dalasi',
                'symbol' => 'D',
                'country' => 'Gambia',
                'cf_code' => 'GM',
                'conversion_rate' => '13.70',
                'is_active' => 1,
                'created_at' => '2026-01-05 18:51:58',
                'updated_at' => '2026-01-05 18:51:58',
            ),
            20 => 
            array (
                'id' => 21,
                'code' => 'GHS',
                'name' => 'Ghanaian Cedi',
                'symbol' => '₵',
                'country' => 'Ghana',
                'cf_code' => 'GH',
                'conversion_rate' => '15.50',
                'is_active' => 1,
                'created_at' => '2026-01-05 18:51:58',
                'updated_at' => '2026-01-05 18:51:58',
            ),
            21 => 
            array (
                'id' => 22,
                'code' => 'GNF',
                'name' => 'Guinean Franc',
                'symbol' => 'FG',
                'country' => 'Guinea',
                'cf_code' => 'GN',
                'conversion_rate' => '1.00',
                'is_active' => 1,
                'created_at' => '2026-01-05 18:51:58',
                'updated_at' => '2026-01-05 18:51:58',
            ),
            22 => 
            array (
                'id' => 23,
                'code' => 'KES',
                'name' => 'Kenyan Shilling',
                'symbol' => 'KSh',
                'country' => 'Kenya',
                'cf_code' => 'KE',
                'conversion_rate' => '13.50',
                'is_active' => 1,
                'created_at' => '2026-01-05 18:51:58',
                'updated_at' => '2026-01-05 18:51:58',
            ),
            23 => 
            array (
                'id' => 24,
                'code' => 'LSL',
                'name' => 'Lesotho Loti',
                'symbol' => 'L',
                'country' => 'Lesotho',
                'cf_code' => 'LS',
                'conversion_rate' => '14.90',
                'is_active' => 1,
                'created_at' => '2026-01-05 18:51:58',
                'updated_at' => '2026-01-05 18:51:58',
            ),
            24 => 
            array (
                'id' => 25,
                'code' => 'LRD',
                'name' => 'Liberian Dollar',
                'symbol' => '$',
                'country' => 'Liberia',
                'cf_code' => 'LR',
                'conversion_rate' => '1.00',
                'is_active' => 1,
                'created_at' => '2026-01-05 18:51:58',
                'updated_at' => '2026-01-05 18:51:58',
            ),
            25 => 
            array (
                'id' => 26,
                'code' => 'LYD',
                'name' => 'Libyan Dinar',
                'symbol' => 'ل.د',
                'country' => 'Libya',
                'cf_code' => 'LY',
                'conversion_rate' => '91.20',
                'is_active' => 1,
                'created_at' => '2026-01-05 18:51:58',
                'updated_at' => '2026-01-05 18:51:58',
            ),
            26 => 
            array (
                'id' => 27,
                'code' => 'MGA',
                'name' => 'Malagasy Ariary',
                'symbol' => 'Ar',
                'country' => 'Madagascar',
                'cf_code' => 'MG',
                'conversion_rate' => '0.00',
                'is_active' => 1,
                'created_at' => '2026-01-05 18:51:58',
                'updated_at' => '2026-01-05 18:51:58',
            ),
            27 => 
            array (
                'id' => 28,
                'code' => 'MWK',
                'name' => 'Malawian Kwacha',
                'symbol' => 'MK',
                'country' => 'Malawi',
                'cf_code' => 'MW',
                'conversion_rate' => '3580.00',
                'is_active' => 1,
                'created_at' => '2026-01-05 18:51:58',
                'updated_at' => '2026-01-05 18:51:58',
            ),
            28 => 
            array (
                'id' => 29,
                'code' => 'MRU',
                'name' => 'Mauritanian Ouguiya',
                'symbol' => 'UM',
                'country' => 'Mauritania',
                'cf_code' => 'MR',
                'conversion_rate' => '3.48',
                'is_active' => 1,
                'created_at' => '2026-01-05 18:51:58',
                'updated_at' => '2026-01-05 18:51:58',
            ),
            29 => 
            array (
                'id' => 30,
                'code' => 'MUR',
                'name' => 'Mauritian Rupee',
                'symbol' => '₨',
                'country' => 'Mauritius',
                'cf_code' => 'MU',
                'conversion_rate' => '3.25',
                'is_active' => 1,
                'created_at' => '2026-01-05 18:51:58',
                'updated_at' => '2026-01-05 18:51:58',
            ),
            30 => 
            array (
                'id' => 31,
                'code' => 'MAD',
                'name' => 'Moroccan Dirham',
                'symbol' => 'د.م',
                'country' => 'Morocco',
                'cf_code' => 'MA',
                'conversion_rate' => '38.00',
                'is_active' => 1,
                'created_at' => '2026-01-05 18:51:58',
                'updated_at' => '2026-01-05 18:51:58',
            ),
            31 => 
            array (
                'id' => 32,
                'code' => 'MZN',
                'name' => 'Mozambican Metical',
                'symbol' => 'MT',
                'country' => 'Mozambique',
                'cf_code' => 'MZ',
                'conversion_rate' => '1.00',
                'is_active' => 1,
                'created_at' => '2026-01-05 18:51:58',
                'updated_at' => '2026-01-05 18:51:58',
            ),
            32 => 
            array (
                'id' => 33,
                'code' => 'NAD',
                'name' => 'Namibian Dollar',
                'symbol' => '$',
                'country' => 'Namibia',
                'cf_code' => 'NA',
                'conversion_rate' => '1.00',
                'is_active' => 1,
                'created_at' => '2026-01-05 18:51:58',
                'updated_at' => '2026-01-05 18:51:58',
            ),
            33 => 
            array (
                'id' => 34,
                'code' => 'NGN',
                'name' => 'Nigerian Naira',
                'symbol' => '₦',
                'country' => 'Nigeria',
                'cf_code' => 'NG',
                'conversion_rate' => '1439.28',
                'is_active' => 1,
                'created_at' => '2026-01-05 18:51:58',
                'updated_at' => '2026-01-05 18:51:58',
            ),
            34 => 
            array (
                'id' => 35,
                'code' => 'RWF',
                'name' => 'Rwandan Franc',
                'symbol' => 'FRw',
                'country' => 'Rwanda',
                'cf_code' => 'RW',
                'conversion_rate' => '1.00',
                'is_active' => 1,
                'created_at' => '2026-01-05 18:51:58',
                'updated_at' => '2026-01-05 18:51:58',
            ),
            35 => 
            array (
                'id' => 36,
                'code' => 'STN',
                'name' => 'São Tomé and Príncipe Dobra',
                'symbol' => 'Db',
                'country' => 'São Tomé and Príncipe',
                'cf_code' => 'ST',
                'conversion_rate' => '1.00',
                'is_active' => 1,
                'created_at' => '2026-01-05 18:51:58',
                'updated_at' => '2026-01-05 18:51:58',
            ),
            36 => 
            array (
                'id' => 37,
                'code' => 'SCR',
                'name' => 'Seychellois Rupee',
                'symbol' => '₨',
                'country' => 'Seychelles',
                'cf_code' => 'SC',
                'conversion_rate' => '1.00',
                'is_active' => 1,
                'created_at' => '2026-01-05 18:51:58',
                'updated_at' => '2026-01-05 18:51:58',
            ),
            37 => 
            array (
                'id' => 38,
                'code' => 'SLL',
                'name' => 'Sierra Leonean Leone',
                'symbol' => 'Le',
                'country' => 'Sierra Leone',
                'cf_code' => 'SL',
                'conversion_rate' => '1.00',
                'is_active' => 1,
                'created_at' => '2026-01-05 18:51:58',
                'updated_at' => '2026-01-05 18:51:58',
            ),
            38 => 
            array (
                'id' => 39,
                'code' => 'SOS',
                'name' => 'Somali Shilling',
                'symbol' => 'Sh',
                'country' => 'Somalia',
                'cf_code' => 'SO',
                'conversion_rate' => '1.00',
                'is_active' => 1,
                'created_at' => '2026-01-05 18:51:58',
                'updated_at' => '2026-01-05 18:51:58',
            ),
            39 => 
            array (
                'id' => 40,
                'code' => 'ZAR',
                'name' => 'South African Rand',
                'symbol' => 'R',
                'country' => 'South Africa',
                'cf_code' => 'ZA',
                'conversion_rate' => '15.00',
                'is_active' => 1,
                'created_at' => '2026-01-05 18:51:58',
                'updated_at' => '2026-01-05 18:51:58',
            ),
            40 => 
            array (
                'id' => 41,
                'code' => 'SSP',
                'name' => 'South Sudanese Pound',
                'symbol' => '£',
                'country' => 'South Sudan',
                'cf_code' => 'SS',
                'conversion_rate' => '130.26',
                'is_active' => 1,
                'created_at' => '2026-01-05 18:51:58',
                'updated_at' => '2026-01-05 18:51:58',
            ),
            41 => 
            array (
                'id' => 42,
                'code' => 'SDG',
                'name' => 'Sudanese Pound',
                'symbol' => '£',
                'country' => 'Sudan',
                'cf_code' => 'SD',
                'conversion_rate' => '500.00',
                'is_active' => 1,
                'created_at' => '2026-01-05 18:51:58',
                'updated_at' => '2026-01-05 18:51:58',
            ),
            42 => 
            array (
                'id' => 43,
                'code' => 'TZS',
                'name' => 'Tanzanian Shilling',
                'symbol' => 'Sh',
                'country' => 'Tanzania',
                'cf_code' => 'TZ',
                'conversion_rate' => '2737.00',
                'is_active' => 1,
                'created_at' => '2026-01-05 18:51:58',
                'updated_at' => '2026-01-05 18:51:58',
            ),
            43 => 
            array (
                'id' => 44,
                'code' => 'TND',
                'name' => 'Tunisian Dinar',
                'symbol' => 'د.ت',
                'country' => 'Tunisia',
                'cf_code' => 'TN',
                'conversion_rate' => '3.28',
                'is_active' => 1,
                'created_at' => '2026-01-05 18:51:58',
                'updated_at' => '2026-01-05 18:51:58',
            ),
            44 => 
            array (
                'id' => 45,
                'code' => 'UGX',
                'name' => 'Ugandan Shilling',
                'symbol' => 'Sh',
                'country' => 'Uganda',
                'cf_code' => 'UG',
                'conversion_rate' => '4200.00',
                'is_active' => 1,
                'created_at' => '2026-01-05 18:51:58',
                'updated_at' => '2026-01-05 18:51:58',
            ),
            45 => 
            array (
                'id' => 46,
                'code' => 'ZMW',
                'name' => 'Zambian Kwacha',
                'symbol' => 'ZK',
                'country' => 'Zambia',
                'cf_code' => 'ZM',
                'conversion_rate' => '1.00',
                'is_active' => 1,
                'created_at' => '2026-01-05 18:51:58',
                'updated_at' => '2026-01-05 18:51:58',
            ),
            46 => 
            array (
                'id' => 47,
                'code' => 'ZWL',
                'name' => 'Zimbabwean Dollar',
                'symbol' => '$',
                'country' => 'Zimbabwe',
                'cf_code' => 'ZW',
                'conversion_rate' => '380.00',
                'is_active' => 1,
                'created_at' => '2026-01-05 18:51:58',
                'updated_at' => '2026-01-05 18:51:58',
            ),
            47 => 
            array (
                'id' => 48,
                'code' => 'USD',
                'name' => 'United States Dollar',
                'symbol' => '$',
                'country' => 'United States',
                'cf_code' => 'USD',
                'conversion_rate' => '1.35',
                'is_active' => 1,
                'created_at' => '2026-01-05 18:51:58',
                'updated_at' => '2026-01-05 18:51:58',
            ),
            48 => 
            array (
                'id' => 49,
                'code' => 'CAD',
                'name' => 'Canadian Dollar',
                'symbol' => '$',
                'country' => 'Canada',
                'cf_code' => 'CA',
                'conversion_rate' => '1.26',
                'is_active' => 1,
                'created_at' => '2026-01-05 18:51:58',
                'updated_at' => '2026-01-05 18:51:58',
            ),
            49 => 
            array (
                'id' => 50,
                'code' => 'GBP',
                'name' => 'British Pound Sterling',
                'symbol' => '£',
                'country' => 'United Kingdom',
                'cf_code' => 'GB',
                'conversion_rate' => '0.73',
                'is_active' => 1,
                'created_at' => '2026-01-05 18:51:58',
                'updated_at' => '2026-01-05 18:51:58',
            ),
            50 => 
            array (
                'id' => 51,
                'code' => 'EUR',
                'name' => 'Euro',
                'symbol' => '€',
                'country' => 'European Union',
                'cf_code' => 'EU',
                'conversion_rate' => '0.85',
                'is_active' => 1,
                'created_at' => '2026-01-05 18:51:58',
                'updated_at' => '2026-01-05 18:51:58',
            ),
            51 => 
            array (
                'id' => 52,
                'code' => 'AUD',
                'name' => 'Australian Dollar',
                'symbol' => '$',
                'country' => 'Australia',
                'cf_code' => 'AU',
                'conversion_rate' => '1.38',
                'is_active' => 1,
                'created_at' => '2026-01-05 18:51:58',
                'updated_at' => '2026-03-07 23:49:59',
            ),
            52 => 
            array (
                'id' => 53,
                'code' => 'SGD',
                'name' => 'Singapore Dollar',
                'symbol' => '$',
                'country' => 'Singapore',
                'cf_code' => 'SG',
                'conversion_rate' => '1.35',
                'is_active' => 1,
                'created_at' => '2026-01-05 18:51:58',
                'updated_at' => '2026-01-05 18:51:58',
            ),
            53 => 
            array (
                'id' => 54,
                'code' => 'JPY',
                'name' => 'Japanese Yen',
                'symbol' => '¥',
                'country' => 'Japan',
                'cf_code' => 'JP',
                'conversion_rate' => '150.00',
                'is_active' => 1,
                'created_at' => '2026-01-05 18:51:58',
                'updated_at' => '2026-01-05 18:51:58',
            ),
        ));
        
        
    }
}