@extends('emails.layout')
@section('title', 'Earnings Report')
@section('banner_color', '#6366f1')
@section('banner_title', 'Earnings Report Ready')
@section('banner_subtitle', 'Your report has been attached to this email')

@section('content')

    <p style="margin:0 0 10px 0; font-size:16px; font-weight:600; color:#111111;">Hi {{ $user->name }},</p>

    <p style="margin:0 0 24px 0; font-size:14px; color:#555555; line-height:1.7;">
        Your earnings report has been generated by the {{ $global['site_name'] }} team.
        Please find the full breakdown attached as a CSV file. You can open it in
        Microsoft Excel, Google Sheets, or any spreadsheet application.
    </p>

    <table width="100%" cellpadding="0" cellspacing="0" border="0"
           style="background-color:#f8fafc; border:1px solid #e2e8f0; border-radius:10px; margin-bottom:24px;">
        <tr>
            <td style="background-color:#f1f5f9; padding:10px 20px; font-size:11px; font-weight:700; text-transform:uppercase; letter-spacing:0.06em; color:#64748b; border-bottom:1px solid #e2e8f0;">
                Report Details
            </td>
        </tr>
        <tr>
            <td style="padding:11px 20px; border-bottom:1px solid #f1f5f9; font-size:13px;">
                <span style="display:inline-block; width:130px; color:#94a3b8; font-weight:500;">Period</span>
                <span style="color:#1e293b; font-weight:600;">{{ $period }}</span>
            </td>
        </tr>
        <tr>
            <td style="padding:11px 20px; border-bottom:1px solid #f1f5f9; font-size:13px;">
                <span style="display:inline-block; width:130px; color:#94a3b8; font-weight:500;">File Name</span>
                <span style="color:#1e293b; font-weight:600;">{{ $filename }}</span>
            </td>
        </tr>
        <tr>
            <td style="padding:11px 20px; border-bottom:1px solid #f1f5f9; font-size:13px;">
                <span style="display:inline-block; width:130px; color:#94a3b8; font-weight:500;">Total Streams</span>
                <span style="color:#1e293b; font-weight:600;">{{ number_format($totalStreams) }}</span>
            </td>
        </tr>
        <tr>
            <td style="padding:11px 20px; border-bottom:1px solid #f1f5f9; font-size:13px;">
                <span style="display:inline-block; width:130px; color:#94a3b8; font-weight:500;">Total Earnings</span>
                <span style="color:#1e293b; font-weight:600;">${{ number_format($totalEarnings, 2) }} USD</span>
            </td>
        </tr>
        <tr>
            <td style="padding:11px 20px; font-size:13px;">
                <span style="display:inline-block; width:130px; color:#94a3b8; font-weight:500;">Generated</span>
                <span style="color:#1e293b; font-weight:600;">{{ now()->format('F j, Y \a\t g:i A') }}</span>
            </td>
        </tr>
    </table>

    <table width="100%" cellpadding="0" cellspacing="0" border="0" style="margin-bottom:24px;">
        <tr>
            <td style="background-color:#f5f3ff; border-left:4px solid #6366f1; border-radius:6px; padding:14px 16px; font-size:13px; color:#4338ca; line-height:1.6;">
                <strong style="display:block; margin-bottom:4px;">Attachment:</strong>
                {{ $filename }} is attached to this email.
            </td>
        </tr>
    </table>

    <p style="margin:0; font-size:14px; color:#555555; line-height:1.7;">
        If you have any questions about your earnings, please contact our support team at
        <a href="mailto:{{ $global['email'] }}" style="color:#6366f1;">{{ $global['email'] }}</a>.
        Do not reply directly to this email.
    </p>

@endsection